name: GRC Controls Framework CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_generate_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Executive Summary (PowerPoint)
        run: python scripts/generate_executive_summary.py

      - name: Upload Executive Summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: executive-summary
          path: presentation/Executive_Risk_Summary.pptx
